- name: Install JDK 8
  package: name=java-1.8.0-openjdk-devel state=present

- name: Download Tomcat
  unarchive:
      src: http://mirror.ox.ac.uk/sites/rsync.apache.org/tomcat/tomcat-9/v9.0.1/bin/apache-tomcat-9.0.1.tar.gz
      dest: /opt/
      owner: vagrant
      group: vagrant
      remote_src: yes
  ignore_errors: yes

- name: Copy JASIG CAS Server project
  copy:
    src: files/jasig-cas
    dest: /home/vagrant
    owner: vagrant
    group: vagrant

- name: Copy Example Tomcat server configuration
  copy:
    src: files/apache-tomcat
    dest: /home/vagrant
    owner: vagrant
    group: vagrant
