- name: NFS Server
  package: name=nfs-utils state=present
  when: ansible_distribution == "CentOS"

- name: NFS Server
  package: name=nfs-kernel-server state=present
  when: ansible_distribution == "Debian"  or ansible_distribution == "Ubuntu"

- name: Start NFS Server
  service: name=nfs-server state=started
  when: ansible_distribution == "CentOS"

- name: Start NFS Server
  service: name=nfs-kernel-server state=started
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Setup NFS Exports Directorys
  file:
    path: /exports/dls/
    state: directory

- name: Setup NFS mount points
  file:
    path: /exports/dls/{{item}}
    state: directory
  with_items:
    - i01
    - i02
    - i03
    - i04

- name: Copy NFS exports file
  copy:
    src: files/exports
    dest: /etc/
