- name: Add MariaDB repository
  yum_repository:
    name: mariadb
    description: MariaDB repo
    baseurl: http://yum.mariadb.org/10.3/centos7-amd64
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: yes

- name: Install MariaDB Server
  yum:
    name: MariaDB-server

- name: Install MariaDB Client
  yum:
    name: MariaDB-client

- name: Install MySQL Python for remote configuration
  yum:
    name: MySQL-python

- name: Start the MariaDB service
  service:
    name: mariadb
    state: started
    enabled: yes
