# Provision root permissions for the MariaDB Server
- name: Remove OLD ISPyB databases
  mysql_db:
    name: "{{item}}"
    state: absent
  with_items:
  - pydb
  - pyconfig

- name: Create ISPyB database
  mysql_db:
    name: "{{ispyb_db_name}}"
    collation: utf8_unicode_ci
    state: present
  ignore_errors: no

- name: Set up ISPyB admin user
  mysql_user:
    name: "{{ispyb_db_user}}"
    password: "{{ispyb_db_password}}"
    host: '%'
    priv: '{{ispyb_db_name}}.*:ALL'
    state: present
  ignore_errors: no

- name: Ensure git is installed
  yum:
    name: git
    state: latest

- name: Checkout ispyb-database from GitHub
  git:
    repo: https://github.com/DiamondLightSource/ispyb-database
    dest: "/tmp/ispyb-database-{{ispyb_db_version}}"
    version: "{{ispyb_db_version}}"
  ignore_errors: no

- name: Import ISPyB tables, routines, and sample data
  mysql_db:
    state: import
    name: "{{ispyb_db_name}}"
    target: "/tmp/ispyb-database-{{ispyb_db_version}}/schema/{{item}}.sql"
  with_items:
  - tables
  - routines
  - lookups
  - data
  ignore_errors: no
