- name: Install JDK 8 CentOS
  package: name=java-1.8.0-openjdk-devel state=present
  when: ansible_distribution == "CentOS"

# Debian version (9 or above jdk 8 needed for apache tomcat 9...)
- name: Install JDK 8 Ubuntu
  package: name=openjdk-8-jdk state=present
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Install Maven (required to build CAS Overlay)
  package: name=maven state=present

- name: Install Git
  package: name=git state=latest

- name: Download Tomcat
  unarchive:
      src: http://www.mirrorservice.org/sites/ftp.apache.org/tomcat/tomcat-9/v{{tomcat_version}}/bin/apache-tomcat-{{tomcat_version}}.tar.gz
      dest: /opt/
      owner: vagrant
      group: vagrant
      remote_src: yes
  ignore_errors: yes

- name: Copy Example Tomcat server configuration
  copy:
    src: files/apache-tomcat
    dest: /home/vagrant
    owner: vagrant
    group: vagrant

- name: Copy Script to generate self-signed key
  copy:
    src: files/scripts
    dest: /home/vagrant
    owner: vagrant
    group: vagrant

- name: Generate self-signed certificate (testing)
  command: sh generate_key.sh creates=/home/vagrant/.keystore
  become: yes
  become_user: vagrant
  args:
    chdir: /home/vagrant/scripts

- name: Tomcat configuration file
  copy:
    src: files/apache-tomcat/conf/server.xml
    dest: /opt/{{tomcat_home}}/conf/

- name: Import Apereo CAS Tasks
  import_tasks: apereo-cas.yml
