  - name: Install Apache
    package: name=httpd state=latest

  - name: Start the Apache Web service
    service: name=httpd state=started enabled=yes

  - name: Install PHP packages
    package:
      name: "{{ item }}"
      state: latest
    with_items:
      - php
      - php-mysql

