# This is the same as install_packages CentOS but with correct package names for Debian/Ubuntu
  - name: Install Apache
    package: name=apache2 state=latest

  - name: Start the Apache Web service
    service: name=apache2 state=started enabled=yes

# Note we need the native driver version (possibly some other ones too...
  - name: Install PHP packages
    package:
      name: "{{ item }}"
      state: latest
    with_items:
      - php5
      - php5-fpm
      - php5-mysqlnd
