# Package Name for git is the same in all distributions
  - name: Install Git
    package: name=git state=latest

  - name: Install Unzip
    package: name=unzip state=latest

  - name: Ensure SynchWeb dir exists
    file:
      path: "{{ synchweb_home }}"
      state: directory

  - name: Checkout Synchweb project
    git:
        repo: "{{ synchweb_repo }}"
        dest: "{{ synchweb_home }}"

  - name: Copy dependencies across (until php composer ready)
    copy: src=files/SynchWeb/lib.zip dest="{{ synchweb_home}}/api/" owner=vagrant group=vagrant mode=0644

  - name: Copy example DLS file system
    copy: src=files/SynchWeb/ispyb-dls-dir.tar.gz dest="/home/vagrant" owner=vagrant group=vagrant mode=0644

  - name: Unarchive the DLS archive
    unarchive:
      src: "/home/vagrant/ispyb-dls-dir.tar.gz"
      dest: "/"
      remote_src: yes

  - name: Unarchive the dependencies
    unarchive:
      src: "{{ synchweb_home}}/api/lib.zip"
      dest: "{{ synchweb_home}}/api/"
      remote_src: yes

  - name: Copy dummy authentication across (until php composer ready)
    copy: src=files/SynchWeb/class.auth-dummy.php dest="{{ synchweb_home}}/api/includes" owner=vagrant group=vagrant mode=0644

  - name: Change ownership to vagrant
    file:
        path: "{{ synchweb_home }}"
        owner: vagrant
        group: vagrant
        recurse: yes

# We need to generate a JWT token for use with synchweb api
  - name: Generate JWT token
    shell: "head -c 64 /dev/urandom | base64 | tr --delete '\n'"
    register: jwt

  - name: Test JWT
    debug:
      msg: "echo {{jwt.stdout}}"

  - name: Update synchweb config.php file
    template: src=files/SynchWeb/config.php.j2 dest="{{ synchweb_home}}/api/config.php" owner=vagrant group=vagrant mode=0644

  - name: Update synchweb config.json file
    template: src=files/SynchWeb/config.json dest="{{ synchweb_home}}/client/js/config.json" owner=vagrant group=vagrant mode=0644
