# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
#

Vagrant.configure("2") do |config|
  # VirtualBox Guest Additions plugin required
  unless Vagrant.has_plugin?("vagrant-vbguest")
    abort "VirtualBox Guest Additions plugin is required. Please run `vagrant plugin install vagrant-vbguest`."
  end

  # CentOS 7 Vagrant box
  # https://app.vagrantup.com/centos/boxes/7
  config.vm.box = "centos/7"
  config.vm.box_version = "1902.01"

  config.vm.define "lamp" do |lamp|
    # Requests to "localhost:9080" forward to port 80 on the guest machine.
    lamp.vm.network "forwarded_port", guest: 80, host: 9080
    lamp.vm.network "forwarded_port", guest: 3306, host: 3306
    lamp.vm.network "private_network", ip: "192.168.33.10"

    # Ports required for CAS role
    lamp.vm.network "forwarded_port", guest: 8080, host: 8080
    lamp.vm.network "forwarded_port", guest: 8443, host: 8443

    lamp.vm.synced_folder "src/", "/var/www/sites/"

    lamp.vm.provision "ansible" do |ansible|
      ansible.compatibility_mode = "2.0"
      ansible.playbook = "../playbooks/standalone.yml"
    end
  end
end
